In [2]:
import redis
import json
import pandas as pd
import numpy as np
import mysql.connector
import pymysql
import pyodbc
import pickle

Note: Run RELATIONAL TWITTER (USERS).ipynd file before running this file. RELATIONAL TWITTER (USERS).ipynd will create the user table that is important for this file

In [ ]:
"""
Queries

Top 10 users with the most followers worldwide
Top 10 verified users in the USA  
Users with the most friends worldwide 
Top 10 users with the most tweets 
Users who have liked the most tweets 
Most followed non-verified accounts 
Top 10 users in a specific location (e.g., London, Tokyo) 
Most active users in terms of tweet frequency """

In [7]:
MYSQL_HOST = "localhost"
MYSQL_USER = "root"
MYSQL_PASSWORD = "Admin"
MYSQL_DATABASE = "twitter_data_"

db = mysql.connector.connect(
    host=MYSQL_HOST,
    user=MYSQL_USER,
    password=MYSQL_PASSWORD,
    database=MYSQL_DATABASE
)

cursor = db.cursor()


#replace 'London' in the top_10_users_specific_location query with the actual location youâ€™re interested in
queries = {
    'top_10_most_followers': """
        SELECT id, name, screen_name, followers_count 
        FROM users 
        ORDER BY followers_count DESC 
        LIMIT 10
    """,
    'top_10_verified_users_USA': """
        SELECT id, name, screen_name, followers_count 
        FROM users 
        WHERE location LIKE '%USA%' AND verified = 1 
        ORDER BY followers_count DESC 
        LIMIT 10
    """,
    'most_friends': """
        SELECT id, name, screen_name, friends_count 
        FROM users 
        ORDER BY friends_count DESC 
        LIMIT 1
    """,
    'top_10_most_tweets': """
        SELECT id, name, screen_name, statuses_count 
        FROM users 
        ORDER BY statuses_count DESC 
        LIMIT 10
    """,
    'most_likes': """
        SELECT id, name, screen_name, favourites_count 
        FROM users 
        ORDER BY favourites_count DESC 
        LIMIT 1
    """,
    'most_followed_non_verified': """
        SELECT id, name, screen_name, followers_count 
        FROM users 
        WHERE verified = 0 
        ORDER BY followers_count DESC 
        LIMIT 1
    """,
    'top_10_users_specific_location': """
        SELECT id, name, screen_name, followers_count 
        FROM users 
        WHERE location LIKE '%London%' 
        ORDER BY followers_count DESC 
        LIMIT 10
    """,
    'most_active_users': """
        SELECT id, name, screen_name, statuses_count/(DATEDIFF(NOW(), created_date)+1) as tweet_frequency 
        FROM users 
        ORDER BY tweet_frequency DESC 
        LIMIT 1
    """
}

results = {}
for query_name, query in queries.items():
    cursor.execute(query)
    results[query_name] = cursor.fetchall()

with open('results.pkl', 'wb') as f:
    pickle.dump(results, f)

print("Results have been cached.")

db.close()


with open('results.pkl', 'rb') as f:
    cached_results = pickle.load(f)

for query_name, result in cached_results.items():
    print(f"\n{query_name}:")
    for row in result:
        print(row)

Results have been cached.

top_10_most_followers:
(69183155, 'detikcom', 'detikcom', 15884929)
(124172948, 'La Patilla', 'la_patilla', 7121282)
(216289357, '               ', 'skynewsarabia', 5652410)
(43568964, 'vir sanghvi', 'virsanghvi', 4329132)
(25401359, 'Noticieros Televisa', 'NTelevisa_com', 3047122)
(18935802, 'Repubblica', 'repubblica', 2992272)
(183253150, 'R M Phoolo', 'casspernyovest', 2702055)
(166522734, '                        ', 'OKAZ_online', 1789175)
(886934161, 'andihiyat', 'andihiyat', 1774024)
(109651819, 'Foro TV', 'Foro_TV', 1661077)

top_10_verified_users_USA:
(16148602, 'Alan W  Silberberg', 'IdeaGov', 24936)
(1850333580, 'Ben Spielberg', 'BenSpielberg', 16481)
(1216767823885803521, 'Tammy K  Orta', 'ortatko', 107)

most_friends:
(68036460, 'Roy Campos', 'RoyCampos', 659218)

top_10_most_tweets:
(124172948, 'La Patilla', 'la_patilla', 5132141)
(113410319, 'Vitor Santos', 'jornalistavitor', 2198168)
(292619181, 'scarlet monahan', 'scarletmonahan', 1899479)
(69183155, 'detikcom', 'detikcom', 1631925)
(118794845, 'Trading MarcoDaCosta', 'MarcoDaCostaFX', 1420281)
(2321317278, 'kekita', 'ElsaKekita', 1312568)
(275754256, 'Tommy Brain  ', 'TommyBrain', 1188780)
(4289217222, 'Steve Brookes MBE', 'SteveBrookesMBE', 1173650)
(1454502163, 'Tommaso Iacobellis   ', 'IacobellisT', 1093266)
(718145940, 'PNR  ', 'CityReport', 1014615)

most_likes:
(707432781492699137, 'Sheila Decker', 'SheilaDecker19', 807395)

most_followed_non_verified:
(886934161, 'andihiyat', 'andihiyat', 1774024)

top_10_users_specific_location:
(19530624, 'Chris Addison', 'mrchrisaddison', 363033)
(19530289, 'Laurie Penny', 'PennyRed', 180215)
(22369602, 'Edward Lucas', 'edwardlucas', 73443)
(2569685214, 'Dr  Kelechi Anyikude', 'KelechiAFC', 46497)
(15342208, 'VoxEU', 'voxeu', 39498)
(544732668, 'Kyle Orton', 'KyleWOrton', 31236)
(2729705377, 'CEPR', 'cepr_org', 25079)
(51378058, 'NotImpressed  FBPE    SardinesUK', 'randombigbird', 11063)
(19785093, 'Sophie Petzal but coughing suspiciously', 'Sonic_Screwup', 8930)
(213243802, 'John O Connell', 'jdpoc', 8344)

most_active_users:
(124172948, 'La Patilla', 'la_patilla', Decimal('996.5322'))